# Generated by Django 3.2.9 on 2021-11-07 15:28

from django.db import migrations


def populate_initial_data(apps, schema_editor):
    Girl = apps.get_model('girl', 'Girl')
    girl1 = Girl()
    girl1.first_name = "Maya"
    girl1.last_name = "Lil"
    girl1.age = 18
    girl1.save()
    girl2 = Girl()
    girl2.first_name = "Jeff"
    girl2.last_name = "Milton"
    girl2.age = 19
    girl2.save()


class Migration(migrations.Migration):

    dependencies = [
        ('girl', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data)
    ]
